/*
CloudTruth Management API

CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.

API version: v1
Contact: support@cloudtruth.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudtruthapi

import (
	"encoding/json"
)

// ParameterExport struct for ParameterExport
type ParameterExport struct {
	// The exported parameter body.
	Body string `json:"body"`
	// If True, the exported parameters include one or more secrets.
	HasSecret bool `json:"has_secret"`
}

// NewParameterExport instantiates a new ParameterExport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParameterExport(body string, hasSecret bool) *ParameterExport {
	this := ParameterExport{}
	this.Body = body
	this.HasSecret = hasSecret
	return &this
}

// NewParameterExportWithDefaults instantiates a new ParameterExport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParameterExportWithDefaults() *ParameterExport {
	this := ParameterExport{}
	return &this
}

// GetBody returns the Body field value
func (o *ParameterExport) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *ParameterExport) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *ParameterExport) SetBody(v string) {
	o.Body = v
}

// GetHasSecret returns the HasSecret field value
func (o *ParameterExport) GetHasSecret() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasSecret
}

// GetHasSecretOk returns a tuple with the HasSecret field value
// and a boolean to check if the value has been set.
func (o *ParameterExport) GetHasSecretOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasSecret, true
}

// SetHasSecret sets field value
func (o *ParameterExport) SetHasSecret(v bool) {
	o.HasSecret = v
}

func (o ParameterExport) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["body"] = o.Body
	}
	if true {
		toSerialize["has_secret"] = o.HasSecret
	}
	return json.Marshal(toSerialize)
}

type NullableParameterExport struct {
	value *ParameterExport
	isSet bool
}

func (v NullableParameterExport) Get() *ParameterExport {
	return v.value
}

func (v *NullableParameterExport) Set(val *ParameterExport) {
	v.value = val
	v.isSet = true
}

func (v NullableParameterExport) IsSet() bool {
	return v.isSet
}

func (v *NullableParameterExport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParameterExport(val *ParameterExport) *NullableParameterExport {
	return &NullableParameterExport{value: val, isSet: true}
}

func (v NullableParameterExport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParameterExport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
