/*
CloudTruth Management API

CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.

API version: v1
Contact: support@cloudtruth.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudtruthapi

import (
	"encoding/json"
)

// AwsPullSyncActionRequest struct for AwsPullSyncActionRequest
type AwsPullSyncActionRequest struct {
	// Allows you to set the dry_run flag on the pull action before triggering a sync.
	DryRun *bool `json:"dry_run,omitempty"`
}

// NewAwsPullSyncActionRequest instantiates a new AwsPullSyncActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsPullSyncActionRequest() *AwsPullSyncActionRequest {
	this := AwsPullSyncActionRequest{}
	return &this
}

// NewAwsPullSyncActionRequestWithDefaults instantiates a new AwsPullSyncActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsPullSyncActionRequestWithDefaults() *AwsPullSyncActionRequest {
	this := AwsPullSyncActionRequest{}
	return &this
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *AwsPullSyncActionRequest) GetDryRun() bool {
	if o == nil || o.DryRun == nil {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsPullSyncActionRequest) GetDryRunOk() (*bool, bool) {
	if o == nil || o.DryRun == nil {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *AwsPullSyncActionRequest) HasDryRun() bool {
	if o != nil && o.DryRun != nil {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *AwsPullSyncActionRequest) SetDryRun(v bool) {
	o.DryRun = &v
}

func (o AwsPullSyncActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DryRun != nil {
		toSerialize["dry_run"] = o.DryRun
	}
	return json.Marshal(toSerialize)
}

type NullableAwsPullSyncActionRequest struct {
	value *AwsPullSyncActionRequest
	isSet bool
}

func (v NullableAwsPullSyncActionRequest) Get() *AwsPullSyncActionRequest {
	return v.value
}

func (v *NullableAwsPullSyncActionRequest) Set(val *AwsPullSyncActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsPullSyncActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsPullSyncActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsPullSyncActionRequest(val *AwsPullSyncActionRequest) *NullableAwsPullSyncActionRequest {
	return &NullableAwsPullSyncActionRequest{value: val, isSet: true}
}

func (v NullableAwsPullSyncActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsPullSyncActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


