/*
CloudTruth Management API

CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.

API version: v1
Contact: support@cloudtruth.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudtruthapi

import (
	"encoding/json"
)

// ParameterTimelineEntryParameter struct for ParameterTimelineEntryParameter
type ParameterTimelineEntryParameter struct {
	// A unique identifier for the parameter.
	Id string `json:"id"`
	// The parameter name.
	Name string `json:"name"`
}

// NewParameterTimelineEntryParameter instantiates a new ParameterTimelineEntryParameter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParameterTimelineEntryParameter(id string, name string) *ParameterTimelineEntryParameter {
	this := ParameterTimelineEntryParameter{}
	this.Id = id
	this.Name = name
	return &this
}

// NewParameterTimelineEntryParameterWithDefaults instantiates a new ParameterTimelineEntryParameter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParameterTimelineEntryParameterWithDefaults() *ParameterTimelineEntryParameter {
	this := ParameterTimelineEntryParameter{}
	return &this
}

// GetId returns the Id field value
func (o *ParameterTimelineEntryParameter) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ParameterTimelineEntryParameter) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ParameterTimelineEntryParameter) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ParameterTimelineEntryParameter) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ParameterTimelineEntryParameter) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ParameterTimelineEntryParameter) SetName(v string) {
	o.Name = v
}

func (o ParameterTimelineEntryParameter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableParameterTimelineEntryParameter struct {
	value *ParameterTimelineEntryParameter
	isSet bool
}

func (v NullableParameterTimelineEntryParameter) Get() *ParameterTimelineEntryParameter {
	return v.value
}

func (v *NullableParameterTimelineEntryParameter) Set(val *ParameterTimelineEntryParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableParameterTimelineEntryParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableParameterTimelineEntryParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParameterTimelineEntryParameter(val *ParameterTimelineEntryParameter) *NullableParameterTimelineEntryParameter {
	return &NullableParameterTimelineEntryParameter{value: val, isSet: true}
}

func (v NullableParameterTimelineEntryParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParameterTimelineEntryParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


